### ISSUE TITLE
Unable to instantiate mediation adapter class.

### ISSUE THREAD

**Issue by TonyAnine** [AndroidDeveloperLB/PhoneCallRecorder#10]
Hello, I saw that you had feedback on the Facebook ad mediation adapter problem before, and I would like to ask you if this problem has been solved. Excuse me. I look forward to your reply.

**Comment by AndroidDeveloperLB** [comment]
I don't remember. I think I talked with them about it somehow.

Anyway, closing this as it's irrelevant to the repository.
