### ISSUE TITLE
Call Recording on a Headset

### ISSUE THREAD

**Issue by epeguero** [AndroidDeveloperLB/PhoneCallRecorder#12]
Hi,

Thanks a lot for open sourcing this solution: this has been instrumental in understanding of how to record calls on Android.

Testing on Android 12 on a Pixel 6, call recording works well. However, when testing with a headset, the phone call receiver's voice is absent from the recording.

Is there any way to fix this issue?

**Comment by AndroidDeveloperLB** [comment]
No idea if it's possible. You should ask this on StackOverflow, but I think that even if you get an answer it will be a workaround that might not work on some devices.
