### ISSUE TITLE
VOIP Calls not recorded

### ISSUE THREAD

**Issue by Zulqurnain** [AndroidDeveloperLB/PhoneCallRecorder#2]
Any suggestions on how can i use this lib to record Voip Calls like whatsapp/facebook etc

**Comment by AndroidDeveloperLB** [comment]
This library is for real phone calls. Not of some third party calling feature. There they can do whatever they wish.

I don't think there is an API from those apps that tells that a Voip call has started or ended. It's not a normal phone call after all. It's their rules after all. You should check their API instead.

However, it might be possible to just record from the microphone, without needing this library at all?
It would be manual, but it's better than nothing... I don't know if it's possible. Worth checking...

**Comment by Zulqurnain** [comment]
Yeah trust me I have tried every possible way I can think of to try recording WhatsApp call, but i couldn't, but apps like CubeARC are doing this, i don't know how

**Comment by AndroidDeveloperLB** [comment]
Maybe like boldbeast call recording app, it uses some weird JNI solutions.

**Comment by AndroidDeveloperLB** [comment]
Where is this "CubeARC " app?

**Comment by Zulqurnain** [comment]
Here you go https://play.google.com/store/apps/details?id=com.catalinagroup.callrecorder 
I tried to contact there team to to let me have a peek of some code, they didn't respond

**Comment by AndroidDeveloperLB** [comment]
I've updated to Android Q, and for some reason this app keeps crashing for me. :(

**Comment by dinhthang12t** [comment]
> Maybe like boldbeast call recording app, it uses some weird JNI solutions.

Do you know more detail about JNI solutions?

**Comment by AndroidDeveloperLB** [comment]
@dinhthang12t Sadly it was a very long time ago that I've even written in JNI.
However, I've found an app developer who have made a solution using JNI, and he has a working app on the Play Store.
