### ISSUE TITLE
please use NDK

### ISSUE THREAD

**Issue by mahdisml** [AndroidDeveloperLB/PhoneCallRecorder#3]
hi ! this app didn't used NDK , and that means it can't record calls in marshmallow and newer versions .

**Comment by AndroidDeveloperLB** [comment]
I don't know what to use there. I'm not familiar with the tidbits that are possible to use on JNI.
I used only the Android framework.
If you know how to add more support via JNI, please show code that you've checked that helps, and I will be able to check it out and add it.

**Comment by mahdisml** [comment]
its there :https://github.com/ViktorDegtyarev/CallRecLib/blob/master/library/src/main/cpp/callrecfix.c
it will work in android 6 but in android 7 and newer versions .
in android 7+ problem is access to **libutils.so** and **libmedia.so** .
and my problem is that .
i saw others can have access to that libs with prebuilt libraries .

**Comment by AndroidDeveloperLB** [comment]
Already tested it on multiple devices. It doesn't help at all, or on devices that he tested it:
https://github.com/ViktorDegtyarev/CallRecLib/issues/15
https://github.com/ViktorDegtyarev/CallRecLib/issues/24

And the code is different than the app that it is said to be based on, especially seeing the difference in time between them.

I've also wrote a very extensive StackOverflow question about it all:
https://stackoverflow.com/questions/50970915/how-do-some-apps-overcome-phone-recording-restrictions

**Comment by mahdisml** [comment]
(ViktorDegtyarev/CallRecLib) library will work if we access to **libutils.so** and **libmedia.so** (they banned in android N)

please see that : https://stackoverflow.com/questions/13115827/how-to-link-to-the-libmedia-so-system-library-in-an-android-ndk-app-using-androi
i think we can solve that problem . (PLAN A)

now im decompiling apps to know how they record a call (for PLAN B)

**Comment by AndroidDeveloperLB** [comment]
@mahdisml I've ran the sample app of the library. It uses the JNI part already (I've checked that it reaches there). The whole point of the sample is to show that it works, but it didn't work for me.
