### ISSUE TITLE
Have you find anythig yet?

### ISSUE THREAD

**Issue by usamanasir-git** [AndroidDeveloperLB/PhoneCallRecorder#5]
We are developing a Dialer app for company's personal use. We need to record calls and we need it on over 200 devices. I found this on GITHUB [](https://github.com/ViktorDegtyarev/CallRecLib). I have tested the app provided with this repository but it works till android 8.1. It is not an easy task to find 3 -4 years old phone in bulk. So we are really in need of a solution for latest android versions.

**Comment by AndroidDeveloperLB** [comment]
No. Please talk to Google. Star or make requests on the issue tracker related to call recording :
https://issuetracker.google.com/issues/new?component=190923&template=841312
